### ISSUE TITLE
generate_voxforge_training_data problem

### ISSUE THREAD

**Issue by Sean861026** [mleimeister/ctc_tensorflow_voxforge#3]
C:\ctc_tensorflow_voxforge-master>python generate_voxforge_training_data.py
Traceback (most recent call last):
  File "generate_voxforge_training_data.py", line 158, in <module>
    batched_data, original_targets = make_batched_data(wav_files, batch_size=4)
  File "generate_voxforge_training_data.py", line 132, in make_batched_data
    features, targets, seq_len, original = extract_features_and_targets(f, txt_file)
  File "generate_voxforge_training_data.py", line 72, in extract_features_and_targets
    fs, audio = wav.read(wav_file)
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\io\wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\io\wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format b'his '... not understood.

**Comment by mleimeister** [comment]
Hi Sean, this looks like a Python 2 vs. 3 problem with string data types. Have you tried running it with Python2?
